FROM rasa/rasa-sdk:3.4.0

WORKDIR /app

COPY ./actions/requirements.txt .

USER root

RUN pip install --no-cache-dir -r requirements.txt

COPY ./actions /app/actions
COPY ./scraper /app/scraper

EXPOSE 5055

CMD ["start", "--actions", "actions"]