FROM rasa/rasa-sdk:3.6.0

USER root

# Instalar dependencias necesarias para tus acciones personalizadas
RUN pip install PyMuPDF==1.22.3 python-docx==1.1.0 pdfplumber==0.9.0

# Volver al usuario no privilegiado por seguridad
USER 1001