FROM rasa/rasa:3.5.14

USER root

# Instalar dependencias para procesamiento de documentos
RUN pip install PyMuPDF==1.21.1 python-docx==0.8.11 pdfplumber==0.9.0

# Instalar spaCy y el modelo de español
RUN pip install spacy && \
    python -m spacy download es_core_news_md

# Volver al usuario no privilegiado por seguridad
USER 1001