FROM rasa/rasa:3.5.14

USER root

# Instalar dependencias para procesamiento de documentos
RUN pip install PyMuPDF==1.21.1 python-docx==0.8.11 pdfplumber==0.9.0

# Volver al usuario no privilegiado por seguridad
USER 1001